name: Backend unit tests

on: [push]

jobs:
  build-lint-and-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        # Add conda to system path
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        conda env update --file env.yml --name base
    # - name: Lint with flake8
    #   run: |
    #     # cd backend
    #     conda install --solver=classic conda-forge::conda-libmamba-solver conda-forge::libmamba conda-forge::libmambapy conda-forge::libarchive
    #     conda install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --statistics --config=${{github.workspace}}/backend/.flake8
    - name: Test
      run: |
        pytest
    - name: Coverage
      run: |
        coverage run --source=src -m pytest
    - name: Coverage report
      run: |
        coverage report -m
        # coverage report --fail-under=90 -m
    - name: Coverage badge
      run: |
        # coverage-badge
        coverage-badge -o ../README.md_images/coverage.svg -f
        coverage-badge -o coverage-badge.svg -f
 
