name: Reusable workflow example

on:
    workflow_call:

jobs:
    coverage-and-report:
        name: Generate coverage and report
        runs-on: ubuntu-latest        
        steps:
            - id: 'Coverage'
                run: coverage run --source=src -m pytest
            - id: 'Coverage report'
                run: coverage report -m
                # coverage report --fail-under=90 -m
            - id: 'Coverage badge'
                run: coverage-badge -o coverage-badge.svg -f
                # coverage-badge
                # coverage-badge -o ../README.md_images/coverage.svg -f
                # coverage-badge -o coverage-badge.svg -f

